[package]
name = "query_api"
version = "0.1.0"
edition = "2018"

[dependencies]
serde_json = "1.0.69"
hyper = { version = "0.14.14", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.13.0", features = ["full"] }
reqwest = { version = "0.11.6", features = ["json", "gzip", "brotli"] }
base64 = { version = "0.13.0" }
hematite-nbt = { version = "0.5.2" }
lazy_static = "1.4.0"
log = "0.4.14"
substring = "1.4.5"
regex = "1.5.4"
futures = "0.3.17"
tokio-postgres = {version = "0.7.5", features = ["with-serde_json-1"] }