[package]
name = "query_api"
version = "1.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.5", features = ["with-serde_json-1"] }
reqwest = { version = "0.11.6", features = ["json", "gzip", "brotli"] }
postgres-types = { version = "0.2.2", features = ["derive", "array-impls"] }
serde = { version = "1.0.130", features = ["derive"] }
dashmap = { version = "4.0.2", features = ["serde"] }
hyper = { version = "0.14.15", features = ["server"]}
hematite-nbt = "0.5.2"
lazy_static = "1.4.0"
simplelog = "0.11.0"
substring = "1.4.5" 
futures = "0.3.17"
base64 = "0.13.0"
dotenv = "0.15.0"
chrono = "0.4.19"
log =  "0.4.14"
regex = "1.5.4"
serde_json = "1.0.72"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"