[package]
name = "query_api"
version = "1.6.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.6", features = ["with-serde_json-1"] }
postgres-types = { version = "0.2.3", features = ["derive", "array-impls"] }
serde = { version = "1.0.139", features = ["derive"] }
dashmap = { version = "5.3.4", features = ["serde"] }
hyper = { version = "0.14.20", features = ["full"] }
hematite-nbt = "0.5.2"
lazy_static = "1.4.0"
simplelog = "0.12.0"
substring = "1.4.5"
futures = "0.3.21"
base64 = "0.13.0"
dotenv = "0.15.0"
chrono = "0.4.19"
log = "0.4.17"
enumset = "*"
regex = "1.6.0"
serde_json = "1.0.82"
surf = { version = "2.3.2", features = ["curl-client"] }
deadpool-postgres = "0.10.2"

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
opt-level = 3
panic = "abort"
