[package]
name = "query_api"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "query_api"
path = "src/a_main.rs"

[dependencies]
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
# tokio-util = "0.6.8"
reqwest = { version="0.11.4", features = ["json", "gzip", "brotli"] }
base64 = {version="0.13.0" }
hematite-nbt = { version="0.5.2" }
lazy_static = "1.4.0"
log="0.4.14"
simplelog = "^0.10.0"
substring="1.4.5"
regex = "1.5.4"
mongodb = "2.0.0"
futures = "0.3.17"